### ISSUE TITLE
how to incorporate django-generate-secret-key?

### ISSUE THREAD

**Issue by soilstack** [MickaelBergem/django-generate-secret-key#3]
I see d-g-s-k is setup as a a pypi repository that I could [install and then import in a python module](https://pypi.python.org/pypi/django-generate-secret-key/1.0.2). 

But I also see that I can install the `management/commands/*` subdirectory under my django app,  then I can call 'create-secret-key' from 'manage.py'.

What is the recommended way to download/incorporate `django-generate-secret-key` into my django project and  git repository?

**Comment by diogosimao** [comment]
Hi!

Looks like it needs to add `'django_generate_secret_key'`  to `INSTALLED_APPS`.

Bye!

**Comment by MickaelBergem** [comment]
I forgot to close the issue but the README has been updated on this GitHub repository.
